[versions]
androidGradlePlugin = "8.7.1"
kotlin = "1.9.0"

[libraries]
# (đây là nơi để khai báo các thư viện thông thường)
appcompat = { module = "androidx.appcompat:appcompat", version = "1.7.0" }
material = { module = "com.google.android.material:material", version = "1.12.0" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version = "2.1.4" }

camera-core = { module = "androidx.camera:camera-core", version = "1.3.4" }
camera-camera2 = { module = "androidx.camera:camera-camera2", version = "1.3.4" }
camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version = "1.3.4" }
camera-view = { module = "androidx.camera:camera-view", version = "1.3.4" }

glide = { module = "com.github.bumptech.glide:glide", version = "4.16.0" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
